apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: be-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-be-app
  minReplicas: 3
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
