apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fe-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: movie-fe-app
  minReplicas: 4
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
