apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-output
data:
  fluentd.conf: |
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    # Source for MongoDB logs
    <source>
      @type tail
      path /var/log/mongodb/mongod.log
      tag mongo
      <parse>
        @type none
      </parse>
    </source>

    # Source for Spring Boot logs
    <source>
      @type tail
      path /var/log/spring-boot/*.log
      tag spring.boot
      <parse>
        @type none
      </parse>
    </source>

    # Send logs from MongoDB to Elasticsearch
    <match  mongo.**>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      logstash_format true
      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/mongo.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match >

    # Send logs from Spring Boot to Elasticsearch
    <match  spring.boot.**>
      @type elasticsearch
      host "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      logstash_format true
      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/springboot.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match >
