apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
type: Opaque
data:
  # mongodb-usernames: YWRtaW4=
  mongodb-passwords: MTIzNDU=
  # database: bW92aWUtYXBpLWRi
  mongodb-root-password: MTIzNDU=
